-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. PROFILES Table (Sync with auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  phone text, -- Added for profile setup
  age_group text, -- Added for profile setup
  gender text, -- Added for profile setup
  region text,
  district text,
  is_pet_owner boolean default false, -- Added for profile setup
  points integer default 0,
  level integer default 1,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.1 POINT TRANSACTIONS Table (Wallet History)
create table point_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  amount integer not null, -- Positive for earning, negative for spending
  type text not null, -- 'survey_reward', 'lottery_prize', 'daily_checkin', 'admin_adjustment'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for point_transactions
alter table point_transactions enable row level security;
create policy "Users can view own transactions." on point_transactions for select using (auth.uid() = user_id);


-- RLS for profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. SURVEYS Table
create table surveys (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null, -- 'politics', 'social', 'economy', 'fun'
  points_reward integer default 10,
  start_date timestamp with time zone default timezone('utc'::text, now()),
  end_date timestamp with time zone,
  is_active boolean default true,
  
  -- AI & Metadata columns (Added)
  news_source_url text,
  image_url text,
  is_anonymous boolean default false,
  created_by text,
  ai_analysis_summary text,
  ai_analysis_pros jsonb,
  ai_analysis_cons jsonb,
  ai_analysis_one_liner text,
  ai_analysis_keywords jsonb,
  seo_title text,
  seo_description text,
  seo_keywords text,
  priority integer default 0,
  change_frequency text,
  is_indexable boolean default true,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for surveys
alter table surveys enable row level security;
create policy "Surveys are viewable by everyone." on surveys for select using (true);
create policy "Only admins or service role can insert surveys." on surveys for insert with check (
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  -- Service role bypasses RLS automatically, but explicit policy helps when using client with RLS
);


-- 3. SURVEY QUESTIONS Table
create table survey_questions (
  id bigint generated by default as identity primary key,
  survey_id bigint references surveys(id) on delete cascade not null,
  question_text text not null,
  question_type text not null, -- 'single_choice', 'multiple_choice'
  options jsonb not null, -- Array of options: ["Option A", "Option B"]
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for survey_questions
alter table survey_questions enable row level security;
create policy "Questions are viewable by everyone." on survey_questions for select using (true);


-- 4. SURVEY VOTES Table (User Participation)
create table survey_votes (
  id bigint generated by default as identity primary key,
  survey_id bigint references surveys(id) on delete cascade not null,
  question_id bigint references survey_questions(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  selected_option_index integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, question_id) -- Prevent duplicate voting per question
);

-- RLS for survey_votes
alter table survey_votes enable row level security;
create policy "Users can view their own votes." on survey_votes for select using (auth.uid() = user_id);
create policy "Authenticated users can vote." on survey_votes for insert with check (auth.uid() = user_id);


-- 5. POLITICIANS Table
create table politicians (
  id bigint generated by default as identity primary key,
  name text not null,
  party text, -- 'Democratic', 'People Power', etc.
  region text,
  position text, -- 'Assembly Member', 'Mayor', etc.
  image_url text,
  bio text,
  likes_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for politicians
alter table politicians enable row level security;
create policy "Politicians are viewable by everyone." on politicians for select using (true);


-- 6. POLITICIAN LIKES Table
create table politician_likes (
  user_id uuid references profiles(id) on delete cascade not null,
  politician_id bigint references politicians(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, politician_id)
);

-- RLS for politician_likes
alter table politician_likes enable row level security;
create policy "Users can see all likes." on politician_likes for select using (true);
create policy "Authenticated users can like." on politician_likes for insert with check (auth.uid() = user_id);
create policy "Users can unlike." on politician_likes for delete using (auth.uid() = user_id);

-- Trigger to update likes_count
create or replace function update_politician_likes()
returns trigger as $$
begin
  if (TG_OP = 'INSERT') then
    update politicians set likes_count = likes_count + 1 where id = new.politician_id;
    return new;
  elsif (TG_OP = 'DELETE') then
    update politicians set likes_count = likes_count - 1 where id = old.politician_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

create trigger on_politician_like
  after insert or delete on politician_likes
  for each row execute procedure update_politician_likes();


-- 7. LOTTERY ROUNDS Table
create table lottery_rounds (
  id bigint generated by default as identity primary key,
  round_number integer not null,
  draw_date timestamp with time zone not null,
  winning_numbers integer[], -- Array of 6 numbers
  total_prize_pool integer default 0,
  status text default 'open', -- 'open', 'completed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for lottery_rounds
alter table lottery_rounds enable row level security;
create policy "Everyone can view lottery rounds." on lottery_rounds for select using (true);

-- 8. LOTTERY TICKETS Table
create table lottery_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  round_id bigint references lottery_rounds(id) on delete cascade not null,
  numbers integer[] not null, -- Array of 6 numbers
  is_winner boolean default false,
  prize_amount integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for lottery_tickets
alter table lottery_tickets enable row level security;
create policy "Users can view their own tickets." on lottery_tickets for select using (auth.uid() = user_id);
create policy "Users can create tickets." on lottery_tickets for insert with check (auth.uid() = user_id);


-- 10. ASSEMBLY BILLS Table
create table assembly_bills (
  id bigint generated by default as identity primary key,
  bill_id text not null,
  bill_name text not null,
  proposer text,
  co_proposers text,
  committee text,
  proc_stage text,
  proposal_date timestamp with time zone,
  detail_link text,
  summary text,
  survey_question text,
  survey_options jsonb,
  survey_id bigint references surveys(id) on delete set null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(bill_id)
);

-- RLS for assembly_bills
alter table assembly_bills enable row level security;
create policy "Everyone can view assembly bills." on assembly_bills for select using (true);
create policy "Only admins or service role can insert bills." on assembly_bills for insert with check (
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
);

-- 11. USER AUTH Table (Legacy/Simple Auth Support)
create table user_auth (
  auth_id text primary key,
  user_type text not null default 'guest', -- 'guest', 'verified', 'admin'
  is_guest boolean default true,
  is_authenticated boolean default false,
  email text unique,
  password text,
  name text,
  phone text unique,
  nickname text,
  
  -- Profile Fields
  age_group text,
  gender text,
  region text,
  city_province text,
  district text,
  job_category text,
  education_level text,
  income_level text,
  marital_status text,
  
  -- Stats
  level_number integer default 1,
  experience_points integer default 0,
  personal_points integer default 0,
  available_lottery_tickets integer default 0,
  
  -- Security
  login_attempts integer default 0,
  locked_until timestamp with time zone,
  last_login_at timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- RLS for user_auth
alter table user_auth enable row level security;
create policy "Public read for user_auth" on user_auth for select using (true); 
create policy "Service role full access user_auth" on user_auth for all using (true);

-- 9. RPC Functions (Dashboard Data)
create or replace function get_home_dashboard()
returns json as $$
declare
  active_participants int;
  latest_surveys json;
  next_lottery_draw json;
begin
  -- 1. Get today's active participants (unique voters today)
  -- Approximation based on recent profile updates or votes
  select count(distinct user_id) into active_participants
  from survey_votes
  where created_at > current_date;
  
  -- If null (no votes), default to 0
  if active_participants is null then
    active_participants := 0;
  end if;

  -- 2. Get latest 2 active surveys
  select json_agg(t) into latest_surveys
  from (
    select id, title, category, created_at
    from surveys
    where is_active = true
    order by created_at desc
    limit 2
  ) t;

  -- 3. Get next lottery draw (first 'open' round)
  select row_to_json(r) into next_lottery_draw
  from (
    select id, round_number, draw_date, total_prize_pool
    from lottery_rounds
    where status = 'open'
    order by draw_date asc
    limit 1
  ) r;

  return json_build_object(
    'active_participants', active_participants,
    'latest_surveys', coalesce(latest_surveys, '[]'::json),
    'next_lottery_draw', next_lottery_draw
  );
end;
$$ language plpgsql security definer;

-- 12. POLITICAL POLLS
create table if not exists political_polls (
  id bigint generated by default as identity primary key,
  poll_type text not null, -- candidate_support, party_support, presidential_approval
  poll_date date not null,
  question text,
  region text,
  sample_size integer,
  survey_org text,
  
  candidate_1 text,
  support_rate_1 numeric,
  candidate_2 text,
  support_rate_2 numeric,
  candidate_3 text,
  support_rate_3 numeric,
  candidate_4 text,
  support_rate_4 numeric,
  candidate_5 text,
  support_rate_5 numeric,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 13. POLITICAL FIGURES
create table if not exists political_figures (
  id bigint generated by default as identity primary key,
  name text not null,
  party text,
  position text,
  region text,
  image_url text,
  description text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 14. ASSEMBLY MEMBERS
create table if not exists assembly_members (
  id bigint generated by default as identity primary key,
  name text not null,
  party text,
  region text, -- constituency
  constituency text, -- specific district
  committee text,
  image_url text,
  description text,
  activity_score numeric default 0,
  -- Contact info
  email text,
  phone text,
  website text,
  facebook text,
  twitter text,
  youtube text,
  blog text,
  
  is_active boolean default true,
  last_updated timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- 15. ASSEMBLY ACTIVITIES
create table if not exists assembly_activities (
  id bigint generated by default as identity primary key,
  member_id bigint references assembly_members(id) on delete cascade not null,
  activity_type text not null, -- bill_proposal, attendance, speech
  title text,
  description text,
  activity_date timestamp with time zone,
  link_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 16. POLITICIAN RATINGS
create table if not exists politician_ratings (
  id bigint generated by default as identity primary key,
  user_id text not null, -- generic text id (auth_id)
  politician_id bigint not null,
  politician_type text not null, -- 'assembly_member', 'political_figure'
  
  communication_rating integer default 0,
  policy_rating integer default 0,
  integrity_rating integer default 0,
  local_dev_rating integer default 0,
  average_rating numeric default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  
  unique(user_id, politician_id, politician_type)
);

-- 17. POLITICIAN COMMENTS
create table if not exists politician_comments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  politician_id bigint not null,
  politician_type text not null,
  content text not null,
  
  like_count integer default 0,
  report_count integer default 0,
  is_filtered boolean default false,
  is_deleted boolean default false,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- 18. COMMENT LIKES
create table if not exists comment_likes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  comment_id bigint references politician_comments(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, comment_id)
);

-- RLS Policies (Simplified for Public Read, Auth Write)
alter table political_polls enable row level security;
create policy "Public read political_polls" on political_polls for select using (true);
create policy "Admin insert political_polls" on political_polls for insert with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

alter table political_figures enable row level security;
create policy "Public read political_figures" on political_figures for select using (true);

alter table assembly_members enable row level security;
create policy "Public read assembly_members" on assembly_members for select using (true);

alter table assembly_activities enable row level security;
create policy "Public read assembly_activities" on assembly_activities for select using (true);

alter table politician_ratings enable row level security;
create policy "Public read politician_ratings" on politician_ratings for select using (true);
create policy "Public insert/update politician_ratings" on politician_ratings for all using (true); 

alter table politician_comments enable row level security;
create policy "Public read politician_comments" on politician_comments for select using (true);
create policy "Public insert/update politician_comments" on politician_comments for all using (true); 

alter table comment_likes enable row level security;
create policy "Public insert/update comment_likes" on comment_likes for all using (true);

-- 19. LOCAL COUNCIL MEMBERS
create table if not exists local_council_members (
  id bigint generated by default as identity primary key,
  name text not null,
  party text,
  city_province text, -- 시도 (e.g., 서울특별시)
  district text, -- 구시군 (e.g., 강남구)
  ward text, -- 선거구 (e.g., 가선거구)
  age integer,
  gender text,
  elected_count integer, -- 당선횟수
  
  -- Contact & Info
  education text,
  career text,
  image_url text,
  
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- RLS for local_council_members
alter table local_council_members enable row level security;
create policy "Public read local_council_members" on local_council_members for select using (true);
create policy "Enable all access for service role on local_council_members" on local_council_members for all using ((select auth.role()) = 'service_role');
-- Disable RLS equivalent for development ease as requested
alter table local_council_members disable row level security;
