/** 홈(/dashboard) 온라인게임 타일 캡처 — 오너 쿠키, 읽기만. 살아 있는 3D 장면이 늦게 붙는지·콘솔 오류가 없는지 본다. `npx tsx scripts/sim-e2e/home-capture.ts [base]` */
import "dotenv/config";
import { createHmac } from "crypto";
import { mkdirSync } from "fs";
import { chromium } from "playwright";
const BASE = process.argv[2] || process.env.E2E_BASE || "http://localhost:5001";
const OUT = process.env.OUT || "/private/tmp/claude-501/-Users-choejeonghwan-rankue-app/5779d2d1-b7e1-40c7-9c95-65cf3e0c9ae9/scratchpad/shots";
const MEMBER = process.env.MEMBER_ID || "02fce921-5170-4c0e-9cc2-5be2906f0bb0";
const secret = process.env.COOKIE_SECRET!;
const sig = (v: string) => createHmac("sha256", secret).update(v).digest("base64").replace(/=+$/, "");
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-webgl", "--ignore-gpu-blocklist"] });
const ctx = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "ko-KR" });
await ctx.addCookies([{ name: "hiq_user_id", value: `s:${MEMBER}.${sig(MEMBER)}`, url: BASE }]);
const page = await ctx.newPage();
const errors: string[] = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
page.on("pageerror", (e) => errors.push("pageerror " + String(e).slice(0, 200)));
await page.goto(`${BASE}/dashboard`, { waitUntil: "networkidle" });
await page.waitForFunction(() => /온라인게임/.test(document.body.innerText), null, { timeout: 30000 });
const tile = page.locator("button", { hasText: "온라인게임" }).first();
await tile.scrollIntoViewIfNeeded();
const early = await tile.evaluate((el) => !!el.querySelector("canvas"));
await page.waitForTimeout(4000);
const late = await tile.evaluate((el) => ({ canvas: !!el.querySelector("canvas"), w: el.querySelector("canvas")?.clientWidth, h: el.querySelector("canvas")?.clientHeight }));
console.log("canvas before idle:", early, "after:", JSON.stringify(late));
await tile.screenshot({ path: `${OUT}/home-tile.png` });
await page.screenshot({ path: `${OUT}/home-full.png`, fullPage: false });
console.log("console errors:", errors.slice(0, 5));
await browser.close();
