/** 진입 화면(카드 셋)·멀티방 목록·멀티방 만들기 로비 캡처 — 오너 쿠키, 읽기만. `npx tsx scripts/sim-e2e/rooms-capture.ts [base]` */
import "dotenv/config";
import { createHmac } from "crypto";
import { mkdirSync } from "fs";
import { chromium } from "playwright";
const BASE = process.argv[2] || process.env.E2E_BASE || "http://localhost:5001";
const OUT = process.env.OUT || "/private/tmp/claude-501/-Users-choejeonghwan-rankue-app/5779d2d1-b7e1-40c7-9c95-65cf3e0c9ae9/scratchpad/shots";
const MEMBER = process.env.MEMBER_ID || "02fce921-5170-4c0e-9cc2-5be2906f0bb0";
const secret = process.env.COOKIE_SECRET!;
const sig = (v: string) => createHmac("sha256", secret).update(v).digest("base64").replace(/=+$/, "");
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "ko-KR" });
await ctx.addCookies([{ name: "hiq_user_id", value: `s:${MEMBER}.${sig(MEMBER)}`, url: BASE }]);
const page = await ctx.newPage();
const text = async () => (await page.evaluate(() => document.body.innerText)).replace(/\n+/g, " | ");
await page.goto(`${BASE}/online-game`, { waitUntil: "networkidle" });
await page.waitForSelector('[data-entry="rooms"]', { timeout: 30000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${OUT}/rooms-1-entry.png`, fullPage: true });
console.log("entry:", (await text()).slice(0, 400));
await page.click('[data-entry="rooms"]');
await page.waitForFunction(() => /열린 방|방을 찾는 중/.test(document.body.innerText), null, { timeout: 15000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${OUT}/rooms-2-list.png` });
console.log("rooms:", page.url(), (await text()).slice(0, 300));
await page.goto(`${BASE}/online-game?lobby=1&public=1`, { waitUntil: "networkidle" });
await page.waitForSelector("#sim-match-password", { timeout: 15000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/rooms-3-lobby-public.png`, fullPage: true });
console.log("lobby public toggle on:", await page.evaluate(() => document.querySelector("#sim-match-public")?.getAttribute("aria-checked") ?? document.querySelector("#sim-match-public")?.getAttribute("data-state")));
await page.goto(`${BASE}/online-game?lobby=1&tab=join&code=123456`, { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
console.log("join prefilled:", await page.evaluate(() => (document.querySelector("#sim-match-code") as HTMLInputElement | null)?.value), (await text()).slice(0, 200));
await page.screenshot({ path: `${OUT}/rooms-4-join-prefilled.png` });
await browser.close();
