// 🤖 Auto-generated by Rangkue Bot
// Date: 2026-02-15 20:30:00 (Structured Update)

import { useMemo } from 'react';
import {
    CRAWLED_MEMBERSHIPS,
    calculateTrend,
    formatPrice,
    extractClubName,
    getClubVariants,
    extractVariantType,
    MembershipItem,
    GolfMembership,
    CondoMembership,
    FitnessMembership
} from '../data/membershipData';


export function useMembershipData(membershipId: string) {
    const membership = useMemo(() =>
        CRAWLED_MEMBERSHIPS.find(m => m.id === membershipId) || CRAWLED_MEMBERSHIPS[0],
        [membershipId]);

    const clubName = useMemo(() => extractClubName(membership.name), [membership.name]);
    const variants = useMemo(() => getClubVariants(clubName, CRAWLED_MEMBERSHIPS), [clubName]);
    const currentVariantType = useMemo(() => extractVariantType(membership.name), [membership.name]);

    const hybridData = useMemo(() => {
        const trend = calculateTrend(membership.id);
        const currentPrice = membership.price.current;
        const changeRate = typeof trend.changeRate === 'string' ? parseFloat(trend.changeRate) : trend.changeRate;
        const changeAmount = Math.floor(currentPrice * (changeRate / 100));

        // 주소 정보 추출 (카테고리별 다를 수 있음, 공통 info.Address가 기본)
        const rawAddress = membership.info.Address || '-';
        const region = rawAddress !== '-'
            ? rawAddress.split(' ').slice(0, 2).join(' ')
            : '정보 확인중';

        // 골프 전용 스펙 추출
        const isGolf = membership.category === 'Golf';
        const golfSpec = isGolf ? (membership as GolfMembership).golfSpec : undefined;
        const condoSpec = membership.category === 'Condo' ? (membership as CondoMembership).condoSpec : undefined;
        const fitnessSpec = membership.category === 'Fitness' ? (membership as FitnessMembership).fitnessSpec : undefined;

        // 홀수, 회원수 등 추출
        const holes = golfSpec?.holeCount || "-";
        const memberCount = golfSpec?.memberCount || "-";
        const openDate = golfSpec?.openDate || "-";

        // 그린피 추출
        const greenFee = golfSpec?.greenFee || {
            member: 0,
            nonMember: 0,
            weekendMember: 0,
            weekendNonMember: 0
        };

        // 혜택 리스트 생성 (UI 표시용)
        const benefitsList: { title: string; desc: string; icon: string; }[] = [];
        if (golfSpec?.privilege) {
            if (golfSpec.privilege.booking) benefitsList.push({ title: "부킹 보장", desc: `월 ${golfSpec.privilege.booking}회 보장`, icon: "📅" });
            if (golfSpec.privilege.summary) benefitsList.push({ title: "회원 혜택", desc: golfSpec.privilege.summary, icon: "⛳" });
        }
        if (condoSpec?.benefits) {
            if (condoSpec.benefits.waterParkDiscount) benefitsList.push({ title: "워터파크", desc: `입장료 ${condoSpec.benefits.waterParkDiscount * 100}% 할인`, icon: "🌊" });
            if (condoSpec.benefits.summary) benefitsList.push({ title: "추가 혜택", desc: condoSpec.benefits.summary, icon: "🎁" });
        }

        // Intro Text Construction
        let introDesc = golfSpec?.desc || '';
        let introFeatures = golfSpec?.features || '';
        const introFeeRemarks = golfSpec?.feeRemarks || '';

        if (condoSpec) {
            const partsDesc: string[] = [];
            if (condoSpec.facilities) partsDesc.push(`[부대시설]\n${condoSpec.facilities}`);
            if (partsDesc.length > 0) introDesc = partsDesc.join('\n\n');

            const partsFeat: string[] = [];
            if (condoSpec.qualification) partsFeat.push(`[입회자격]\n${condoSpec.qualification}`);
            if (condoSpec.availableTypes) partsFeat.push(`[회원권 종류]\n${condoSpec.availableTypes}`);
            if (condoSpec.remarks) partsFeat.push(`[특이사항]\n${condoSpec.remarks}`);
            if (partsFeat.length > 0) introFeatures = partsFeat.join('\n\n');
        }

        return {
            id: membership.id,
            name: membership.name,
            type: isGolf ? golfSpec?.type : membership.category, // 정회원 등
            category: membership.category,
            courseType: membership.category,
            region: region,
            originalRegion: region.split(' ')[0],
            holes: holes,
            grass: "-",
            imageUrl: isGolf
                ? "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&q=80&w=2070"
                : membership.category === 'Condo'
                    ? "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=2070"
                    : "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=2070",
            phone: membership.info.homepage || "-",
            tags: membership.tags.length > 0 ? membership.tags.map(t => `#${t}`) : ["#프리미엄"],
            difficulty: "-",
            difficultyDesc: "코스 상세 분석은 회원 가입 후 확인하실 수 있습니다.",
            specs: { speed: 0, fee: 0 },
            currentPrice: currentPrice,
            changeAmount: changeAmount,
            changeRate: changeRate.toFixed(2),
            status: trend.status,
            trendData: [160, 162, 158, 165, 170, 172, 168, 175, 180, 182, 185],
            buyPrice: formatPrice(currentPrice - 5000000), // 매수 호가 (추정)
            sellPrice: formatPrice(currentPrice + 5000000), // 매도 호가 (추정)
            highPrice: formatPrice(membership.price.highYear || 0), // 연간 최고가
            lowPrice: formatPrice(membership.price.lowYear || 0),   // 연간 최저가

            conditions: ["상세 조건은 문의 바랍니다."],
            greenFee: greenFee,
            feeTable: golfSpec?.feeTable, // 상세 요금표 (배열)

            fees: {
                transfer: membership.fees.transfer,
                // 계산기 호환을 위해 commissionRate를 임의 계산 (예: 0.3%) 혹은 절대값 사용
                commission: membership.fees.commission,
                commissionRate: 0.003, // 임시 고정값 (UI 계산용)
                taxRate: membership.fees.acquisitionTaxRate || 0.022,
                caddy: golfSpec?.caddyFee || 0,
                cart: golfSpec?.cartFee || 0
            },

            intro: {
                desc: introDesc,
                features: introFeatures,
                feeRemarks: introFeeRemarks
            },

            clubInfo: {
                // 기존 컴포넌트 호환용 객체 재구성
                memberCount: memberCount,
                website: membership.info.homepage || '',
                address: rawAddress,
                openDate: openDate,
                vendor: membership.info.vendor,
                phone: membership.info.phone,
                operatingHours: membership.info.operatingHours,
                closedDays: membership.info.closedDays
            },
            openDate: openDate,
            address: rawAddress,

            privilege: golfSpec?.privilege,
            benefits: benefitsList,

            // 추가 스펙 데이터 전달 (컴포넌트에서 활용 가능하도록)
            spec: isGolf ? golfSpec : (condoSpec || fitnessSpec)
        };
    }, [membership]);

    return {
        membership,
        variants,
        currentVariantType,
        hybridData
    };
}
