// 🤖 Auto-generated by Rangkue Bot
// Date: 2026-02-15 20:30:00 (Structured Update)

import { useMemo } from 'react';
import {
    CRAWLED_MEMBERSHIPS,
    formatPrice,
    realPrice,
    membershipAsOfLabel,
    extractClubName,
    getClubVariants,
    extractVariantType,
    MembershipItem,
    GolfMembership,
    CondoMembership,
    FitnessMembership
} from '../data/membershipData';

/**
 * 홈페이지 주소 — 자료에 적힌 값 가운데 http(s) 로 시작하는 주소만 내보낸다(2026-10-06).
 * 이 값은 링크의 href 로 나간다(클럽 정보의 웹사이트 줄, 전화번호가 없는 종목의 하단 '홈페이지 보기').
 * 앞뒤 공백은 걷는다(자료에 끝 공백이 붙은 값이 있다). 다른 스킴·스킴 없는 글자·'-' 같은 빈 표시는 빈 값으로 돌려 링크를 그리지 않게 한다 —
 * 주소를 짐작해 고쳐 쓰지 않는다.
 * 호스트 끝이 최상위 도메인 꼴(영문 2~6자)이 아니면 빈 값이다 — 자료에 점이 빠진 값("http://www.seoseoulcokr")이 한 건 있어,
 * 점 하나만 보던 예전 거름을 통과해 '홈페이지 보기'가 없는 호스트로 열렸다. IP 주소·user@ 꼴 호스트도 같이 걸러진다(자료에는 없다).
 */
export const membershipHomepage = (raw: unknown): string => {
    if (typeof raw !== 'string') return '';
    const url = raw.trim();
    return /^https?:\/\/(?:[^\s/?#.:@]+\.)+[a-z]{2,6}(?::\d+)?(?:[/?#]\S*)?$/i.test(url) ? url : '';
};


export function useMembershipData(membershipId: string) {
    const membership = useMemo(() =>
        CRAWLED_MEMBERSHIPS.find(m => m.id === membershipId) || CRAWLED_MEMBERSHIPS[0],
        [membershipId]);

    const clubName = useMemo(() => extractClubName(membership.name), [membership.name]);
    const variants = useMemo(() => getClubVariants(clubName, CRAWLED_MEMBERSHIPS), [clubName]);
    const currentVariantType = useMemo(() => extractVariantType(membership.name), [membership.name]);

    const hybridData = useMemo(() => {
        // 시세는 자료에 실제로 있는 값만 넘긴다: 현재가 · 연간 최고 · 연간 최저.
        // 전일 대비·호가·추이는 이 자료에 없다 — 예전엔 여기서 지어냈고(id 로 만든 등락, 현재가 ±500만 '호가', 고정 추이 배열) 2026-10-06 에 뺐다.
        const currentPrice = membership.price.current;
        const yearHigh = realPrice(membership.price.highYear);
        const yearLow = realPrice(membership.price.lowYear);

        // 주소 정보 추출 (카테고리별 다를 수 있음, 공통 info.Address가 기본)
        const rawAddress = membership.info.Address || '-';
        const region = rawAddress !== '-'
            ? rawAddress.split(' ').slice(0, 2).join(' ')
            : '정보 확인중';

        // 골프 전용 스펙 추출
        const isGolf = membership.category === 'Golf';
        const golfSpec = isGolf ? (membership as GolfMembership).golfSpec : undefined;
        const condoSpec = membership.category === 'Condo' ? (membership as CondoMembership).condoSpec : undefined;
        const fitnessSpec = membership.category === 'Fitness' ? (membership as FitnessMembership).fitnessSpec : undefined;

        // 홀수, 회원수 등 추출
        const holes = golfSpec?.holeCount || "-";
        const memberCount = golfSpec?.memberCount || "-";
        const openDate = golfSpec?.openDate || "-";

        // 그린피 추출
        const greenFee = golfSpec?.greenFee || {
            member: 0,
            nonMember: 0,
            weekendMember: 0,
            weekendNonMember: 0
        };

        // 혜택 리스트 생성 (UI 표시용)
        const benefitsList: { title: string; desc: string; icon: string; }[] = [];
        if (golfSpec?.privilege) {
            if (golfSpec.privilege.booking) benefitsList.push({ title: "부킹 보장", desc: `월 ${golfSpec.privilege.booking}회 보장`, icon: "📅" });
            if (golfSpec.privilege.summary) benefitsList.push({ title: "회원 혜택", desc: golfSpec.privilege.summary, icon: "⛳" });
        }
        if (condoSpec?.benefits) {
            if (condoSpec.benefits.waterParkDiscount) benefitsList.push({ title: "워터파크", desc: `입장료 ${condoSpec.benefits.waterParkDiscount * 100}% 할인`, icon: "🌊" });
            if (condoSpec.benefits.summary) benefitsList.push({ title: "추가 혜택", desc: condoSpec.benefits.summary, icon: "🎁" });
        }

        // Intro Text Construction
        let introDesc = golfSpec?.desc || '';
        let introFeatures = golfSpec?.features || '';
        const introFeeRemarks = golfSpec?.feeRemarks || '';

        if (condoSpec) {
            const partsDesc: string[] = [];
            if (condoSpec.facilities) partsDesc.push(`[부대시설]\n${condoSpec.facilities}`);
            if (partsDesc.length > 0) introDesc = partsDesc.join('\n\n');

            const partsFeat: string[] = [];
            if (condoSpec.qualification) partsFeat.push(`[입회자격]\n${condoSpec.qualification}`);
            if (condoSpec.availableTypes) partsFeat.push(`[회원권 종류]\n${condoSpec.availableTypes}`);
            if (condoSpec.remarks) partsFeat.push(`[특이사항]\n${condoSpec.remarks}`);
            if (partsFeat.length > 0) introFeatures = partsFeat.join('\n\n');
        }

        return {
            id: membership.id,
            name: membership.name,
            type: isGolf ? golfSpec?.type : membership.category, // 정회원 등
            category: membership.category,
            courseType: membership.category,
            region: region,
            originalRegion: region.split(' ')[0],
            holes: holes,
            grass: "-",
            imageUrl: isGolf
                ? "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&q=80&w=2070"
                : membership.category === 'Condo'
                    ? "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=2070"
                    : "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=2070",
            // 전화는 자료에 실제로 있는 번호만(2026-10-06). 예전엔 여기에 홈페이지 주소를 넣어, 전화 단추가 tel:http://… 로 걸리고
            // 번호 자리에 주소가 찍혔다. 번호가 없으면 빈 값 — 하단 단추는 번호가 있으면 전화, 없으면 홈페이지(clubInfo.website),
            // 둘 다 없으면 그리지 않는다(MembershipActionFooter).
            // 자료의 번호는 "02-559-7531~2"·"02-450-4605/02-2022-0048"처럼 여럿이 붙어 있기도 해서, 걸 수 있게 첫 번호 하나만 넘긴다.
            // 홈페이지는 clubInfo.website 로, 적힌 그대로의 번호는 clubInfo.phone 으로 따로 나간다.
            phone: (membership.info.phone || "").split(/[/~,]/)[0].trim(),
            // 태그도 자료에 있는 것만 — 비어 있으면 빈 채로 둔다(예전엔 빈 자리를 같은 태그 하나로 채워 모든 골프장에 붙었다).
            tags: membership.tags.map(t => `#${t}`),
            difficulty: "-",
            difficultyDesc: "코스 상세 분석은 회원 가입 후 확인하실 수 있습니다.",
            specs: { speed: 0, fee: 0 },
            currentPrice: currentPrice,
            highPrice: yearHigh != null ? formatPrice(yearHigh) : null, // 연간 최고가 — 자료에 없으면 null(화면은 칸을 그리지 않는다)
            lowPrice: yearLow != null ? formatPrice(yearLow) : null,    // 연간 최저가 — 위와 같다
            priceAsOfLabel: membershipAsOfLabel(), // "2026.02.15 자료 기준" — 자료 날짜를 모르면 null

            conditions: ["상세 조건은 문의 바랍니다."],
            greenFee: greenFee,
            feeTable: golfSpec?.feeTable, // 상세 요금표 (배열)

            fees: {
                transfer: membership.fees.transfer,
                // 계산기 호환을 위해 commissionRate를 임의 계산 (예: 0.3%) 혹은 절대값 사용
                commission: membership.fees.commission,
                commissionRate: 0.003, // 임시 고정값 (UI 계산용)
                taxRate: membership.fees.acquisitionTaxRate || 0.022,
                caddy: golfSpec?.caddyFee || 0,
                cart: golfSpec?.cartFee || 0
            },

            intro: {
                desc: introDesc,
                features: introFeatures,
                feeRemarks: introFeeRemarks
            },

            clubInfo: {
                // 기존 컴포넌트 호환용 객체 재구성
                memberCount: memberCount,
                website: membershipHomepage(membership.info.homepage), // http(s) 주소만 — 아니면 빈 값(링크를 그리지 않는다)
                address: rawAddress,
                openDate: openDate,
                vendor: membership.info.vendor,
                phone: membership.info.phone,
                operatingHours: membership.info.operatingHours,
                closedDays: membership.info.closedDays
            },
            openDate: openDate,
            address: rawAddress,

            privilege: golfSpec?.privilege,
            benefits: benefitsList,

            // 추가 스펙 데이터 전달 (컴포넌트에서 활용 가능하도록)
            spec: isGolf ? golfSpec : (condoSpec || fitnessSpec)
        };
    }, [membership]);

    return {
        membership,
        variants,
        currentVariantType,
        hybridData
    };
}
