// 🤖 Auto-generated by Rangkue Bot
// Date: 2026-02-03 01:06:58
// Source: Mship114

import { MembershipItem, MembershipCategory } from './crawledMembershipData';
export type { MembershipItem, MembershipCategory };



// 가격 포맷팅 유틸리티
export const formatPrice = (priceValue: number): string => {
    const eok = Math.floor(priceValue / 100000000);  // 억
    const man = Math.floor((priceValue % 100000000) / 10000);  // 만

    if (eok > 0) {
        if (man > 0) {
            return `${eok}억 ${man.toLocaleString()}만`;
        }
        return `${eok}억`;
    }
    if (man > 0) {
        return `${man.toLocaleString()}만`;
    }
    return `${priceValue.toLocaleString()}원`;
};

// 재판매 리스트 생성 (크롤링 데이터로부터)
// 실제 데이터는 별도 파일에서 import
export { CRAWLED_MEMBERSHIPS } from './crawledMembershipData';

// 골프장 이름 추출 (회원권 종류 제거)
// 골프장 이름 추출 (회원권 종류 제거)
export const extractClubName = (fullName: string): string => {
    return fullName
        // 1. 괄호로 묶인 내용 제거 (가장 먼저 처리)
        // (3인), (분2억3천) 등 괄호 안의 패턴 처리 강화
        .replace(/\s*\(.*?(미납|분양|만기|반환|소멸|입회|주중|특별|회원|금액|억|천|만|인|명).*?\)\s*$/g, '')
        // 2. 주요 회원권 종류 및 수식어 제거
        .replace(/\s+(개인|법인|일반|우대|주주|분\d+천?|YES.*|골드창립|창립|VIP|VVIP|노블리안|스마트|프라임|플러스|특별|정회원|준회원|주중|프리빌리지|로얄|헤리티지|통합|비지니스|비즈니스|기여회원|기여|주식|입회|분담금|하나로).*$/g, '')
        // 3. 인원/가족 구성 관련 키워드 제거
        .replace(/\s+(부부|가족|남자|여자|남여|기명|무기명|\d+인).*$/g, '')
        // 4. 금액 패턴 제거 (억, 천, 만 단위가 포함된 경우 - 예: 3억, 5천, 1억2천)
        .replace(/\s+\d+(?:억|천|만)[\d\s]*(?:무기명|기명|통합).*$/g, '')
        .replace(/\s+\d+(?:억|천|만).*$/g, '')
        // 5. 평형 정보, 차수 (소수점 포함 1.2차 등)
        .replace(/\s+\d+[\d/]*평.*$/g, '')
        .replace(/\s+[\d.]+(차|0?만원).*$/g, '')
        // 6. 단순 숫자만 남은 경우
        .replace(/\s+\d+$/g, '')
        // 7. 마지막 정리
        .replace(/\s+(부부|가족|개인|법인)$/g, '')
        .trim();
};

// 회원권 종류만 추출
export const extractVariantType = (fullName: string): string => {
    const clubName = extractClubName(fullName);
    return fullName.replace(clubName, '').trim();
};

// 같은 골프장의 모든 회원권 찾기
export const getClubVariants = (clubName: string, memberships: MembershipItem[]): MembershipItem[] => {
    return memberships.filter(m => extractClubName(m.name) === clubName);
};

// 골프장별로 그룹화 (리스트 심플화용)
export const groupByClub = (memberships: MembershipItem[]): Map<string, MembershipItem[]> => {
    const grouped = new Map<string, MembershipItem[]>();

    memberships.forEach(membership => {
        const clubName = extractClubName(membership.name);
        if (!grouped.has(clubName)) {
            grouped.set(clubName, []);
        }
        grouped.get(clubName)!.push(membership);
    });

    return grouped;
};

// 골프장별 대표 회원권 (가장 저렴한 것)
export const getRepresentativeMemberships = (memberships: MembershipItem[]): MembershipItem[] => {
    const grouped = groupByClub(memberships);
    const representatives: MembershipItem[] = [];

    grouped.forEach((variants) => {
        // 가장 저렴한 회원권을 대표로 선택
        const cheapest = variants.reduce((min, current) =>
            current.priceValue < min.priceValue ? current : min
        );
        representatives.push(cheapest);
    });

    return representatives;
};

// 가격 범위 표시 (최저가 ~ 최고가)
export const getPriceRange = (variants: MembershipItem[]): string => {
    if (variants.length === 1) {
        return formatPrice(variants[0].priceValue);
    }

    const prices = variants.map(v => v.priceValue);
    const min = Math.min(...prices);
    const max = Math.max(...prices);

    return `${formatPrice(min)} ~`;
};

// 시세 변동 상태 계산 (모의 데이터 - 실제로는 API에서 가져와야 함)
export const calculateTrend = (id: string) => {
    const seed = parseInt(id) || 1;
    const isUp = seed % 3 !== 0;
    const isFlat = seed % 7 === 0;

    const status = isFlat ? "FLAT" : (isUp ? "UP" : "DOWN");
    const rate = isFlat ? 0 : (0.3 + (seed % 20) / 10);
    const change = isFlat ? "0.0%" : `${rate.toFixed(2)}%`;

    return {
        status,
        change: status === "UP" ? `+${change}` : (status === "DOWN" ? `-${change}` : change),
        changeRate: rate
    };
};

// 신규 분양 목록 (기존 유지)
export const PRESALE_LIST = [
    {
        id: 101,
        name: "카스카디아 CC",
        title: "창립 특별회원 모집 (마감임박)",
        price: "5억 5,000만",
        dDay: "D-3",
        tag: "무기명 4인",
        region: "강원 홍천",
        image: "https://images.unsplash.com/photo-1628611124619-3c727c9e13e5?q=80&w=2000&auto=format&fit=crop"
    },
    {
        id: 102,
        name: "한림용인 CC",
        title: "리조트형 풀구좌 분양",
        price: "2억 2,000만",
        dDay: "선착순",
        tag: "주말부킹 월3회",
        region: "경기 용인",
        image: "https://images.unsplash.com/photo-1592919505780-30395071d480?q=80&w=2000&auto=format&fit=crop"
    },
];
